### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by uiosun** [zhangbc97/tushare-integration#2]
环境：MySQL [8.0.36-0ubuntu0.22.04.1]
系统：Ubuntu in WSL2
Python 版本：3.10.2

尝试获取日线或分钟线，均报错（详细内容，参考 `runtime.log`）：

```
2024-05-29 10:00:52 [scrapy.core.scraper] ERROR: Error processing {'data':       exchange    cal_date  is_open pretrade_date
…………
11627      DCE  1993-03-01        1    1970-01-01

[11628 rows x 4 columns]}
Traceback (most recent call last):
  File "/home/uiosun/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/uiosun/.local/lib/python3.10/site-packages/scrapy/utils/defer.py", line 340, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/home/uiosun/code/python/tushare-integration/tushare_integration/pipelines.py", line 120, in process_item
    self.db_engine.upsert(self.table_name, data.columns.tolist(), data)
  File "/home/uiosun/code/python/tushare-integration/tushare_integration/db_engine.py", line 70, in upsert
    duplicate_keys=schema['duplicate_keys'],

TypeError: list indices must be integers or slices, not str
```

[runtime.log](https://github.com/zhangbc97/tushare-integration/files/15477782/runtime.log)

**Comment by zhangbc97** [comment]
感谢反馈，目前该项目对MySQL的支持测试尚不完善，可能会存在诸多潜在的BUG，后期会对MySQL采集相关的代码进行优化。目前临时修复了一个版本，但是由于近期精力有限没办法进行完整的测试，十分抱歉~
