### ISSUE TITLE
clickhouse_connect.driver.exceptions.ProgrammingError: Unrecognized column 'open' in table daily

### ISSUE THREAD

**Issue by uiosun** [zhangbc97/tushare-integration#9]
按文档往 ClickHouse 里拉数据，然后先执行了 `python main.py run job stock/basic`

再开始执行 `python main.py run job stock/quotes` 时，开始报错：

```sh
2024-11-07 13:30:59 [scrapy.crawler] INFO: Received SIGINT, shutting down gracefully. Send again to force
2024-11-07 13:30:59 [scrapy.core.engine] INFO: Closing spider (shutdown)
2024-11-07 13:30:59 [scrapy.core.scraper] ERROR: Error processing {'data':      ts_code  trade_date   open   high    low  close  pre_close  change  pct_chg   vol  amount
0  600651.SH  1990-12-27  393.4  393.4  393.4  393.4      389.5     3.9      1.0  66.0   104.0}
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\Py311\Lib\site-packages\twisted\internet\defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\anaconda3\envs\Py311\Lib\site-packages\scrapy\utils\defer.py", line 340, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Py311\tushare-integration\tushare_integration\pipelines.py", line 124, in process_item
    self.db_engine.upsert(self.table_name, schema=self.schema, data=data)
  File "D:\Code\Py311\tushare-integration\tushare_integration\db_engine.py", line 124, in upsert
    self.client.insert_df(table_name, data)
  File "D:\Software\anaconda3\envs\Py311\Lib\site-packages\clickhouse_connect\driver\client.py", line 656, in insert_df
    return self.insert(table,
           ^^^^^^^^^^^^^^^^^^
  File "D:\Software\anaconda3\envs\Py311\Lib\site-packages\clickhouse_connect\driver\client.py", line 614, in insert
    context = self.create_insert_context(table,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\anaconda3\envs\Py311\Lib\site-packages\clickhouse_connect\driver\client.py", line 731, in create_insert_context
    raise ProgrammingError(f'Unrecognized column {ex} in table {table}') from None
clickhouse_connect.driver.exceptions.ProgrammingError: Unrecognized column 'open' in table daily
```

**Comment by zhangbc97** [comment]
数据库的表是通过项目自动创建的嘛？看报错是数据库表中没有open这个字段
连接到数据库执行下
 ```
SHOW CREATE TABLE daily
```

**Comment by uiosun** [comment]
> 数据库的表是通过项目自动创建的嘛？看报错是数据库表中没有open这个字段 连接到数据库执行下
> 
> ```
> SHOW CREATE TABLE daily
> ```

对，自动创建

没有，我自己把 daily 任务的字段补了一下，一个都没有

**Comment by uiosun** [comment]
目前跑到了复权指数任务，除了 daily 任务，其他的一切正常，都自动创建了

**Comment by zhangbc97** [comment]
感谢反馈，我排查一下问题

**Comment by uiosun** [comment]
补充：

1. 在脚本执行中，有中断脚本的行为；
2. 在脚本执行中，我将 `concurrent_requests: 1` 更改为 `concurrent_requests: 2`，后续没感到效率有很大变化
3. 在执行 stock/quotes 前，改回 `concurrent_requests: 1`

**Comment by uiosun** [comment]
> 补充：
> 
> 1. 在脚本执行中，有中断脚本的行为；
> 2. 在脚本执行中，我将 `concurrent_requests: 1` 更改为 `concurrent_requests: 2`，后续没感到效率有很大变化
> 3. 在执行 stock/quotes 前，改回 `concurrent_requests: 1`

为了解决时区问题，换库重新跑了一次，确定这个 issue 跟这些行为没关系

**Comment by uiosun** [comment]
发现了很鬼畜的情况，`daily` 这个表最初是按 `stk_limit` 表的字段创建的，但表名的确是 `daily`

是这个原因导致日线数据不会自动创建表吗？

**Comment by zhangbc97** [comment]
> 发现了很鬼畜的情况，`daily` 这个表最初是按 `stk_limit` 表的字段创建的，但表名的确是 `daily`
> 
> 是这个原因导致日线数据不会自动创建表吗？

建表语句里面带有IF NOT EXISTS的判断，如果已经存在了表就不会重复创建了，但是具体为什么建表的时候字段有问题还需要排查一下

**Comment by uiosun** [comment]
已提交 PR，问题原因：

“日爬取类”有默认的表名设置。
`stk_premarket` 任务继承了日爬取类，但未定义自己的 TABLE，导致表名直接继承。

这个 Issue 的问题不好排查，后续考虑添加功能：`logging` 日志持久化。
